on: [push, pull_request]

name: Continuous Integration

jobs:
  test:
    name: Test
    runs-on: windows-latest
    strategy:
      matrix:
        version:
          - stable
          - 1.43.0
        arch:
          - x86_64
          - i686
        env:
          - msvc
          - gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.version }}-${{ matrix.arch }}-pc-windows-${{ matrix.env }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  test-minimal-versions:
    name: Test (Minimal versions)
    runs-on: windows-latest
    strategy:
      matrix:
        toolchain:
          - nightly-x86_64-pc-windows-msvc
          - nightly-i686-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -Z minimal-versions
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -Z minimal-versions

  # Check with cargo feature features=dev_dep to avoid issues like #7.
  check-features-dev_dep:
    name: Check with -Z features=dev_dep
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: -Z features=dev_dep

  fmt:
    name: Rustfmt
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Use fixed version because format result can change between different rust versions.
          toolchain: 1.46.0
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Use fixed version because clippy warnings can change between rust versions.
          toolchain: 1.46.0
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-targets -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-default-features --all --all-targets -- -D warnings

  check-generated-code:
    name: Check Generated Code (make sure they are up to date)
    # Using bash from ubuntu is easier.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Use fixed version because format result can change between different rust versions.
          toolchain: 1.46.0
          override: true
      - run: rustup component add rustfmt
      - run: cargo run < ../../Microsoft.Web.WebView2.0.9.622.11/WebView2.idl > ../src/lib.rs && rustfmt ../src/lib.rs
        working-directory: webview2-sys/idl2rs
      - run: cargo run -- interface_wrappers < ../../Microsoft.Web.WebView2.0.9.622.11/WebView2.idl > ../../src/interfaces.rs && rustfmt ../../src/interfaces.rs
        working-directory: webview2-sys/idl2rs
      - run: git diff --exit-code
